// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Servika.Infrastructure.Persistence;

#nullable disable

namespace Servika.Infrastructure.Migrations
{
    [DbContext(typeof(ServikaDbContext))]
    [Migration("20260704003706_AddReferrals")]
    partial class AddReferrals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Servika.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ArtisanId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtisanName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.PrimitiveCollection<List<string>>("CompletionPhotoKeys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("InitialQuoteAmountNaira")
                        .HasColumnType("integer");

                    b.Property<string>("LocationInstructions")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double?>("LocationLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocationLng")
                        .HasColumnType("double precision");

                    b.Property<string>("PaymentState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("PreferredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredTimeSlot")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PricingModel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("WorkSubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Catalogue.ArtisanKyc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdDocumentKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelfieKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("artisan_kyc", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Catalogue.ArtisanProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.PrimitiveCollection<List<string>>("CategorySlugs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.PrimitiveCollection<List<string>>("GalleryKeys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("InspectionFeeNaira")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("JobsCount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("ResponseTime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Services")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategorySlugs");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategorySlugs"), "gin");

                    b.HasIndex("UserId");

                    b.ToTable("artisan_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            About = "Professional electrician specializing in installations, repairs and maintenance. Committed to quality work and customer safety.",
                            Accent = "#F97316",
                            CategorySlugs = new List<string> { "electrical" },
                            DistanceKm = 1.2,
                            ExperienceYears = 6,
                            FullName = "Emeka Okafor",
                            GalleryKeys = new List<string> { "electrician", "hvac", "fridge", "carpenter" },
                            ImageKey = "emeka-okafor",
                            InspectionFeeNaira = 5000,
                            IsAvailable = true,
                            JobsCount = "120+",
                            Latitude = 6.4478,
                            Location = "Lagos, Nigeria",
                            Longitude = 3.4723000000000002,
                            Rating = 4.7999999999999998,
                            ResponseTime = "15 min",
                            ReviewCount = 124,
                            Services = new List<string> { "Installation", "Repair", "Maintenance", "Wiring" },
                            Specialty = "Electrical Specialist",
                            UserId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            About = "Experienced plumber handling installations, leak repairs and pipe maintenance. Reliable, neat and available for emergencies.",
                            Accent = "#3B82F6",
                            CategorySlugs = new List<string> { "plumbing" },
                            DistanceKm = 2.2999999999999998,
                            ExperienceYears = 8,
                            FullName = "Ibrahim Yusuf",
                            GalleryKeys = new List<string> { "plumber", "fridge", "electrician", "carpenter" },
                            ImageKey = "ibrahim-yusuf",
                            InspectionFeeNaira = 4000,
                            IsAvailable = true,
                            JobsCount = "200+",
                            Latitude = 6.5095000000000001,
                            Location = "Lagos, Nigeria",
                            Longitude = 3.3711000000000002,
                            Rating = 4.9000000000000004,
                            ResponseTime = "10 min",
                            ReviewCount = 98,
                            Services = new List<string> { "Leak Repair", "Installation", "Drainage", "Maintenance" },
                            Specialty = "Plumbing Expert",
                            UserId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            VerificationStatus = "Verified"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            About = "Certified HVAC technician for AC servicing, installation and gas refill. Focused on efficient cooling and long-term reliability.",
                            Accent = "#10B981",
                            CategorySlugs = new List<string> { "ac", "fridge" },
                            DistanceKm = 3.1000000000000001,
                            ExperienceYears = 5,
                            FullName = "Chidi Okeke",
                            GalleryKeys = new List<string> { "hvac", "fridge", "electrician", "plumber" },
                            ImageKey = "chidi-okeke",
                            InspectionFeeNaira = 6000,
                            IsAvailable = false,
                            JobsCount = "90+",
                            Latitude = 6.6017999999999999,
                            Location = "Lagos, Nigeria",
                            Longitude = 3.3515000000000001,
                            Rating = 4.7000000000000002,
                            ResponseTime = "20 min",
                            ReviewCount = 76,
                            Services = new List<string> { "AC Servicing", "Installation", "Gas Refill", "Repair" },
                            Specialty = "AC Technician",
                            UserId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            VerificationStatus = "Verified"
                        });
                });

            modelBuilder.Entity("Servika.Domain.Catalogue.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconKey")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Tint")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("service_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsPopular = true,
                            Name = "Electrical",
                            Slug = "electrical",
                            SortOrder = 1,
                            Tint = "#F59E0B"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsPopular = true,
                            Name = "Plumbing",
                            Slug = "plumbing",
                            SortOrder = 2,
                            Tint = "#3B82F6"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsPopular = true,
                            Name = "AC Repair",
                            Slug = "ac",
                            SortOrder = 3,
                            Tint = "#0EA5E9"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            IsPopular = true,
                            Name = "Fridge Repair",
                            Slug = "fridge",
                            SortOrder = 4,
                            Tint = "#06B6D4"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            IsPopular = true,
                            Name = "Generator",
                            Slug = "generator",
                            SortOrder = 5,
                            Tint = "#8B5CF6"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            IsPopular = true,
                            Name = "Solar",
                            Slug = "solar",
                            SortOrder = 6,
                            Tint = "#F97316"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            IsPopular = true,
                            Name = "Painting",
                            Slug = "painting",
                            SortOrder = 7,
                            Tint = "#EC4899"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            IsPopular = true,
                            Name = "Carpentry",
                            Slug = "carpentry",
                            SortOrder = 8,
                            Tint = "#A16207"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Appliance Repair",
                            Slug = "appliance",
                            SortOrder = 9,
                            Tint = "#14B8A6"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Cleaning",
                            Slug = "cleaning",
                            SortOrder = 10,
                            Tint = "#22C55E"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Welding",
                            Slug = "welding",
                            SortOrder = 11,
                            Tint = "#EF4444"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Tiling",
                            Slug = "tiling",
                            SortOrder = 12,
                            Tint = "#6366F1"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000013"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Roofing",
                            Slug = "roofing",
                            SortOrder = 13,
                            Tint = "#0EA5E9"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000014"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "CCTV & Security",
                            Slug = "security",
                            SortOrder = 14,
                            Tint = "#64748B"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000015"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Pest Control",
                            Slug = "pest-control",
                            SortOrder = 15,
                            Tint = "#16A34A"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000016"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Locksmith",
                            Slug = "locksmith",
                            SortOrder = 16,
                            Tint = "#CA8A04"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000017"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Electronics",
                            Slug = "electronics",
                            SortOrder = 17,
                            Tint = "#3B82F6"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000018"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Satellite & TV",
                            Slug = "satellite",
                            SortOrder = 18,
                            Tint = "#0891B2"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000019"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Plastering",
                            Slug = "plastering",
                            SortOrder = 19,
                            Tint = "#A16207"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000020"),
                            IsActive = true,
                            IsPopular = false,
                            Name = "Water Pumps",
                            Slug = "water-pump",
                            SortOrder = 20,
                            Tint = "#2563EB"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000021"),
                            IconKey = "tire",
                            IsActive = true,
                            IsPopular = false,
                            Name = "Vulcanizer",
                            Slug = "vulcanizer",
                            SortOrder = 21,
                            Tint = "#334155"
                        });
                });

            modelBuilder.Entity("Servika.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountNaira")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ArtisanId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorizationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Payments.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountNaira")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("wallet_transactions", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Payments.Withdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AccountNumberMasked")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("AmountNaira")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArtisanId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtisanId");

                    b.HasIndex("UserId");

                    b.ToTable("withdrawals", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Referrals.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EarnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferredUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferrerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardNaira")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReferredUserId")
                        .IsUnique();

                    b.HasIndex("ReferrerUserId");

                    b.ToTable("referrals", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtisanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ArtisanId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Tracking.TrackingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtisanProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LastAccuracy")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastHeading")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastSpeed")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("LastUpdateAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("UX_tracking_active_per_booking")
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("tracking_sessions", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ReferralCode")
                        .IsUnique()
                        .HasFilter("\"ReferralCode\" IS NOT NULL");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "emeka.okafor@artisan.servika.test",
                            EmailVerifiedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FullName = "Emeka Okafor",
                            PasswordHash = "$2a$12$nPLo4sZMl89KcvqqJUMcHuUgfVOIeVcVLaBqejV9sQjGqT7X8IriG",
                            PhoneNumber = "+2348100000001",
                            Role = "Artisan"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ibrahim.yusuf@artisan.servika.test",
                            EmailVerifiedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FullName = "Ibrahim Yusuf",
                            PasswordHash = "$2a$12$nPLo4sZMl89KcvqqJUMcHuUgfVOIeVcVLaBqejV9sQjGqT7X8IriG",
                            PhoneNumber = "+2348100000002",
                            Role = "Artisan"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "chidi.okeke@artisan.servika.test",
                            EmailVerifiedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FullName = "Chidi Okeke",
                            PasswordHash = "$2a$12$nPLo4sZMl89KcvqqJUMcHuUgfVOIeVcVLaBqejV9sQjGqT7X8IriG",
                            PhoneNumber = "+2348100000003",
                            Role = "Artisan"
                        });
                });

            modelBuilder.Entity("Servika.Domain.Users.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash");

                    b.HasIndex("UserId", "Purpose");

                    b.ToTable("verification_codes", (string)null);
                });

            modelBuilder.Entity("Servika.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Servika.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Catalogue.ArtisanKyc", b =>
                {
                    b.HasOne("Servika.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Catalogue.ArtisanProfile", b =>
                {
                    b.HasOne("Servika.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Servika.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Servika.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Payments.Payment", b =>
                {
                    b.HasOne("Servika.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Payments.Withdrawal", b =>
                {
                    b.HasOne("Servika.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Referrals.Referral", b =>
                {
                    b.HasOne("Servika.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReferredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Reviews.Review", b =>
                {
                    b.HasOne("Servika.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Tracking.TrackingSession", b =>
                {
                    b.HasOne("Servika.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("Servika.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servika.Domain.Users.VerificationCode", b =>
                {
                    b.HasOne("Servika.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
